version: '3'
services:
  web:
    build:
      context: .
    container_name: web
    ports:
      - "9320:5000"
    links:
      - mongo

  mongo:
       image: mongo
       container_name: mongo
       ports:
         - "27017:27017"

  consumer:
    image: php:apache  
    volumes:
      - ./consumer:/var/www/html 
    ports:
         - "9420:80"
    depends_on:
         - web
